export const states = ["Alaska", "American Samoa", "Arizona", "Arknsas", "California",
                "Colorado", "Florida", "Hawaii", "Idaho", "Kentucky",
                "Indiana", "Maine", "Michigan", "Minnesota", "Missouri",
                "Montana", "Nevada", "New Mexico", "NorthDakota", "North Carolina",
                "Ohio", "Oregon", "South Carolina", "South Dakota", "Tennessee",
                "Texas", "Utah", "Virgin Islands", "Virginia", "Washington",
                "West Virginia", "Wyoming"];

export const stateCodes = {"Alaska": "AK", "American Samoa": "AS", "Arizona": "AZ",
                    "Arknsas": "AR", "California": "CA", "Colorado": "CO",
                    "Florida": "FL", "Hawaii": "HI", "Idaho": "ID",
                    "Kentucky": "KY", "Indiana": "IN", "Maine": "ME",
                    "Michigan": "MI", "Minnesota": "MN", "Missouri": "MO",
                    "Montana": "MT", "Nevada": "NV", "New Mexico": "NM",
                    "North Carolina": "NC", "North Dakota": "ND", "Ohio": "OH",
                    "Oregon": "OR", "South Carolina": "SC", "South Dakota": "SD",
                    "Tennessee": "TN", "Texas": "TX", "Utah": "UT",
                    "Virgin Islands": "VI", "Virginia": "VA", "Washington": "WA",
                    "West Virginia": "WV", "Wyoming": "WY"};

export const parks  = [
  "Acadia National Park", "Arches National Park", "Badlands National Park",
  "Big Bend National Park", "Biscayne National Park", "Black Canyon of the Gunnison National Park",
  "Bryce Canyon National Park", "Canyonlands National Park", "Capitol Reef National Park",
  "Carlsbad Caverns National Park", "Channel Islands National Park", "Congaree National Park",
  "Crater Lake National Park", "Cuyahoga Valley National Park", "Death Valley National Park",
  "Denali National Park and Preserve", "Dry Tortugas National Park", "Everglades National Park",
  "Gates of the Arctic National Park", "Gateway Arch National Park", "Glacier National Park",
  "Glacier Bay National Park", "Grand Canyon National Park", "Grand Teton National Park",
  "Great Basin National Park", "Great Sand Dunes National Park and Preserve", "Great Smoky Mountains National Park",
  "Guadalupe Mountains National Park", "Haleakala National Park", "Hawaii Volcanoes National Park",
  "Hot Springs National Park", "Indiana Dunes National Park", "Isle Royale National Park",
  "Joshua Tree National Park", "Katmai National Park and Preserve", "Kenai Fjords National Park",
  "Kings Canyon National Park", "Kobuk Valley National Park", "Lake Clark National Park",
  "Lassen Volcanic National Park", "Mammoth Cave National Park", "Mesa Verde National Park",
  "Mount Rainier National Park", "National Park of American Samoa", "New River Gorge National Park",
  "North Cascades National Park", "Olympic National Park", "Petrified Forest National Park",
  "Pinnacles National Park", "Redwood National Park", "Rocky Mountain National Park",
  "Saguaro National Park", "Sequoia National Park", "Shenandoah National Park",
  "Theodore Roosevelt National Park", "Virgin Islands National Park", "Voyageurs National Park",
  "White Sands National Park", "Wind Cave National Park", "Wrangell-St. Elias National Park and Preserve",
  "Yellowstone National Park", "Yosemite National Park", "Zion National Park"
];

export const parksWStates  = {
  "Acadia National Park": ["ME"],
  "Arches National Park": ["UT"],
  "Badlands National Park": ["SD"],
  "Big Bend National Park": ["TX"],
  "Biscayne National Park": ["FL"],
  "Black Canyon of the Gunnison National Park": ["CO"],
  "Bryce Canyon National Park": ["UT"],
  "Canyonlands National Park": ["UT"],
  "Capitol Reef National Park": ["UT"],
  "Carlsbad Caverns National Park": ["NM"],
  "Channel Islands National Park": ["CA"],
  "Congaree National Park": ["SC"],
  "Crater Lake National Park": ['OR'],
  "Cuyahoga Valley National Park": ["OH"],
  "Death Valley National Park": ["CA", "NV"],
  "Denali National Park and Preserve": ["AK"],
  "Dry Tortugas National Park": ["FL"],
  "Everglades National Park": ["FL"],
  "Gates of the Arctic National Park": ["AK"],
  "Gateway Arch National Park": "MO",
  "Glacier National Park": "MT",
  "Glacier Bay National Park": ["AK"],
  "Grand Canyon National Park": ["AZ"],
  "Grand Teton National Park": ["WY"],
  "Great Basin National Park": ["NV"],
  "Great Sand Dunes National Park and Preserve": ["CO"],
  "Great Smoky Mountains National Park": ["NC", "TN"],
  "Guadalupe Mountains National Park": ["TX"],
  "Haleakala National Park": ["HI"],
  "Hawaii Volcanoes National Park": ["HI"],
  "Hot Springs National Park": ["AR"],
  "Indiana Dunes National Park": ["IN"],
  "Isle Royale National Park": ["MI"],
  "Joshua Tree National Park": ["CA"],
  "Katmai National Park and Preserve": ["AK"],
  "Kenai Fjords National Park": ["AK"],
  "Kings Canyon National Park": ["CA"],
  "Kobuk Valley National Park": ["AK"],
  "Lake Clark National Park": ["AK"],
  "Lassen Volcanic National Park": ["CA"],
  "Mammoth Cave National Park": ["KY"],
  "Mesa Verde National Park": ["CO"],
  "Mount Rainier National Park": ["WA"],
  "National Park of American Samoa": ["AS"],
  "New River Gorge National Park": ["WV"],
  "North Cascades National Park": ["WA"],
  "Olympic National Park": ["WA"],
  "Petrified Forest National Park": ["AZ"],
  "Pinnacles National Park": ["CA"],
  "Redwood National Park": ["CA"],
  "Rocky Mountain National Park": ["CO"],
  "Saguaro National Park": ["AZ"],
  "Sequoia National Park": ["CA"],
  "Shenandoah National Park": ["VA"],
  "Theodore Roosevelt National Park": ["ND"],
  "Virgin Islands National Park": ["VI"],
  "Voyageurs National Park": ["MN"],
  "White Sands National Park": ["NM"],
  "Wind Cave National Park": ["SD"],
  "Wrangell-St. Elias National Park and Preserve": ["AK"],
  "Yellowstone National Park": ["ID", "MT", "WY"],
  "Yosemite National Park": ["CA"],
  "Zion National Park": ["UT"]
};

export const activties = [
  "activites", "from", "backend", "/activites", "w/ no params"
];